[tool.black]
line-length = 79
include = 'TheengsGateway\/.*\.pyi?$'
[[tool.mypy.overrides]]
module = [
    "Cryptodome.Cipher",
    "Cryptodome.Cipher.AES",
    "paho.mqtt",
    "setuptools",
    "TheengsDecoder",
]
ignore_missing_imports = true
[build-system]
requires = ["setuptools", "wheel"]
