select = [
  "ANN",     # flake8-annotations
  "BLE",     # flake8-blind-except
  "D",       # pydocstyle
  "E",       # pycodestyle
  "EM",      # flake8-errmsg
  "F",       # Pyflakes
  "SIM",     # flake8-simplify
  "TRY",     # Tryceratops
]
ignore = [
  "ANN101",  # missing-type-self
  "D107",    # undocumented-public-init
]
# Always generate Python 3.7-compatible code
target-version = "py37"

[pydocstyle]
convention = "google"
