select = [
  "ANN",     # flake8-annotations
  "D",       # pydocstyle
  "E",       # pycodestyle
  "F",       # Pyflakes
]
ignore = [
  "ANN101",  # missing-type-self
  "D107",    # undocumented-public-init
]
# Always generate Python 3.7-compatible code
target-version = "py37"

[pydocstyle]
convention = "google"
