select = [
  "D",     # pydocstyle
  "E",     # pycodestyle
  "F",     # Pyflakes
]
ignore = [
  "D107",  # undocumented-public-init
]
# Always generate Python 3.7-compatible code
target-version = "py37"

[pydocstyle]
convention = "google"
