name: Create and publish documentation
on:
  workflow_dispatch:
  release:
    types: [published]
jobs:
  documentation:
    runs-on: ubuntu-22.04
    name: Create the documentation and deploy it to GitHub Pages
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "14.x"
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
          npm install
      - name: Download Common Config
        run: |
          curl -o docs/.vuepress/public/commonConfig.js https://www.theengs.io/commonConfig.js
      - name: Build documentation
        run: |
          npm run docs:build
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/.vuepress/dist
          cname: gateway.theengs.io
